Vagrant.configure("2") do |config|
    config.vm.box_download_insecure = true
    config.vm.define "machine1" do |machine1|
        machine1.vm.box = "ubuntu/trusty64"
        machine1.vm.hostname = "UbuntuDesk"
        machine1.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vp.cpus = "1"
        end
        machine1.vm.provision "shell", path: "bootstrap.sh"
    end

    config.vm.define "machine2" do |machine2|
        machine2.vm.box = "centos/8"
        machine2.vm.hostname = "CentOs"
        machine2.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = "1"
        end
        machine2.vm.provision "shell", path: "bootstrapCent.sh"
    end
end